$RootDir = Split-Path -Parent $MyInvocation.MyCommand.Definition

$EngineSourceDir = Join-Path $RootDir "Engine\Source"
$BuilderDir      = Join-Path $RootDir "Engine\Builder"
$OutputFile      = Join-Path $BuilderDir "GeneratedIncludeFiles.cs"

Write-Host "------------------------------------------------" -ForegroundColor Cyan
Write-Host "Auto-Generating Includes..." -ForegroundColor Cyan
Write-Host "Root: $RootDir" -ForegroundColor Gray

if (-not (Test-Path $BuilderDir)) { New-Item -ItemType Directory -Path $BuilderDir | Out-Null }

$Content = @"
// ========================================================================
// Limitless Engine Notice:
// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT.
// Generated by GenerateIncludes.ps1
// ========================================================================

using Sharpmake;

"@

$BuilderUri = New-Object System.Uri ($BuilderDir + "\")

if (Test-Path $EngineSourceDir) {
    $Files = Get-ChildItem -Path $EngineSourceDir -Recurse -Filter "*.Build.cs"

    foreach ($File in $Files) {
        $FileUri = New-Object System.Uri $File.FullName
        $RelativeUri = $BuilderUri.MakeRelativeUri($FileUri)
        $RelativePath = [System.Uri]::UnescapeDataString($RelativeUri.ToString())

        if ($RelativePath -notlike "*GeneratedIncludeFiles.cs*" -and 
            $RelativePath -notlike "*Engine.Build.cs*" -and 
            $RelativePath -notlike "*Globals.cs*") {
            Write-Host "  [+] Mounted: $RelativePath" -ForegroundColor Green
            $Content += "[module: Sharpmake.Include(`"$RelativePath`")]`n"
        }
    }
} else {
    Write-Host "  [!] Warning: Engine/Source not found!" -ForegroundColor Red
}

$Content | Out-File -FilePath $OutputFile -Encoding UTF8
Write-Host "Done. Written to Engine/Builder/GeneratedIncludeFiles.cs" -ForegroundColor Yellow
Write-Host "------------------------------------------------" -ForegroundColor Cyan