#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BUILDER_DIR="$ROOT_DIR/Engine/Builder"
SOURCE_DIR="$ROOT_DIR/Engine/Source"
OUTPUT_FILE="$BUILDER_DIR/GeneratedIncludeFiles.cs"
SHARPMAKE_ROOT="$ROOT_DIR/External/Sharpmake"
SHARPMAKE_PROJECT="$SHARPMAKE_ROOT/Sharpmake.Application/Sharpmake.Application.csproj"
SHARPMAKE_CONFIG="${SHARPMAKE_CONFIG:-Release}"
SHARPMAKE_FRAMEWORK="${SHARPMAKE_FRAMEWORK:-net8.0}"
SHARPMAKE_OUTPUT_DIR="$SHARPMAKE_ROOT/Sharpmake.Application/bin/$SHARPMAKE_CONFIG/$SHARPMAKE_FRAMEWORK"
MAIN_SCRIPT="Engine/Builder/LimitlessBuilder.cs"

echo "[1/3] Auto-discovering modules..."

mkdir -p "$BUILDER_DIR"

{
    cat <<'EOF'
// ========================================================================
// Limitless Engine Notice:
// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT.
// Generated by GenerateProject.sh
// ========================================================================

using Sharpmake;

EOF

    while IFS= read -r file; do
        relative_from_root="${file#"$ROOT_DIR"/}"
        relative_path="../${relative_from_root#Engine/}"
        printf '[module: Sharpmake.Include("%s")]\n' "$relative_path"
    done < <(find "$SOURCE_DIR" -name '*.Build.cs' | sort)
} > "$OUTPUT_FILE"

echo "Generated $OUTPUT_FILE"
echo
echo "[2/4] Validating Sharpmake toolchain..."

if [[ ! -d "$SHARPMAKE_ROOT" ]]; then
    echo "Error: Sharpmake submodule not found at $SHARPMAKE_ROOT." >&2
    echo "Run: git submodule update --init --recursive" >&2
    exit 1
fi

if ! command -v dotnet >/dev/null 2>&1; then
    echo "Error: dotnet SDK is required to build and run Sharpmake on macOS." >&2
    echo "Install dotnet, then rerun ./GenerateProject.sh." >&2
    exit 1
fi

echo
echo "[3/4] Building Sharpmake..."
dotnet build "$SHARPMAKE_PROJECT" -c "$SHARPMAKE_CONFIG" -nologo

if [[ -x "$SHARPMAKE_OUTPUT_DIR/Sharpmake.Application" ]]; then
    SHARPMAKE_CMD=("$SHARPMAKE_OUTPUT_DIR/Sharpmake.Application")
elif [[ -f "$SHARPMAKE_OUTPUT_DIR/Sharpmake.Application.dll" ]]; then
    SHARPMAKE_CMD=(dotnet "$SHARPMAKE_OUTPUT_DIR/Sharpmake.Application.dll")
else
    echo "Error: Sharpmake build finished but no runnable output was found." >&2
    echo "Expected one of:" >&2
    echo "  $SHARPMAKE_OUTPUT_DIR/Sharpmake.Application" >&2
    echo "  $SHARPMAKE_OUTPUT_DIR/Sharpmake.Application.dll" >&2
    exit 1
fi

echo
echo "[4/4] Running Sharpmake for macOS/Xcode..."
"${SHARPMAKE_CMD[@]}" "/sources('$MAIN_SCRIPT')"

echo
echo "Done! Generated Sharpmake project files for macOS."
