struct VSOutput
{
    float4 Position : SV_Position;
    [[vk::location(0)]] float2 Uv : TEXCOORD0;
};

VSOutput MainVS(uint vertexId : SV_VertexID)
{
    const float2 positions[3] = {
        float2(-1.0, -1.0),
        float2( 3.0, -1.0),
        float2(-1.0,  3.0)
    };

    VSOutput output;
    const float2 position = positions[vertexId];
    output.Position = float4(position, 0.0, 1.0);
    output.Uv = position * 0.5 + 0.5;
    return output;
}
