// ========================================================================
// Limitless Engine Notice:
// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT.
// Generated by GenerateIncludes.ps1
// ========================================================================

using Sharpmake;
[module: Sharpmake.Include("../Source/Runtime/Core/Core.Build.cs")]
[module: Sharpmake.Include("../Source/Runtime/Launch/Launch.Build.cs")]
[module: Sharpmake.Include("../Source/Runtime/RAL/RAL.Build.cs")]
[module: Sharpmake.Include("../Source/Runtime/RFG/RFG.Build.cs")]
[module: Sharpmake.Include("../Source/ThirdParty/Glm/Glm.Build.cs")]
[module: Sharpmake.Include("../Source/ThirdParty/Spdlog/Spdlog.Build.cs")]
[module: Sharpmake.Include("../Source/ThirdParty/Vulkan/Vulkan.Build.cs")]

