import * as ChildProcess from "node:child_process";
import * as Fs from "node:fs/promises";
import * as Path from "node:path";
import type { BuildAction, Target } from "../Configuration/Types.ts";
import { FindNinjaExecutable } from "../Toolchain/ExecutableLocator.ts";
import type { IToolchain } from "../Toolchain/IToolchain.ts";
import type { BackendResult, BuildOptions, GenerateOptions, IBackend } from "./IBackend.ts";

const FlagsWithPaths = ["/LIBPATH:", "/OUT:", "/I", "/Fo", "/Fd", "/Fe", "/Fi", "/Yc", "/Yu", "/Fm"];

function QuoteToken(Token: string): string {
    if (!Token.includes(" ")) {
        return Token;
    }
    for (const Flag of FlagsWithPaths) {
        if (Token.startsWith(Flag)) {
            return `${Flag}"${Token.slice(Flag.length)}"`;
        }
    }
    return `"${Token}"`;
}

function ToNinjaPath(FilePath: string): string {
    return FilePath.replace(/\\/g, "/").replace(/:/g, "$:");
}

export class NinjaBackend implements IBackend {
    public readonly Name = "Ninja";
    private readonly Toolchain: IToolchain;

    public constructor(Toolchain: IToolchain) {
        this.Toolchain = Toolchain;
    }

    public async Generate(
        Actions: BuildAction[],
        Target: Target,
        Options: GenerateOptions,
    ): Promise<BackendResult> {
        await Fs.mkdir(Options.OutputDir, { recursive: true });

        const NinjaPath = Path.join(Options.OutputDir, "build.ninja");
        await Fs.writeFile(NinjaPath, this.BuildNinjaFile(Actions, Target), "utf-8");

        const CompileCommandsPath = Options.CompileCommandsPath
            ?? Path.join(Options.OutputDir, "compile_commands.json");
        await Fs.writeFile(
            CompileCommandsPath,
            JSON.stringify(this.BuildCompileCommands(Actions), null, 2),
            "utf-8",
        );

        return {
            Actions,
            NinjaPath,
            CompileCommandsPath,
            CompileCount: Actions.filter((Action) => Action.Type === "compile").length,
            LinkCount: Actions.filter((Action) => Action.Type === "link" || Action.Type === "archive").length,
        };
    }

    public async Build(Result: BackendResult, Options: BuildOptions): Promise<number> {
        const NinjaExecutable = FindNinjaExecutable();
        if (!NinjaExecutable) {
            throw new Error("ninja was not found on PATH. Install Ninja or set LIMITLESS_BUILDER_NINJA to its executable path.");
        }

        const Environment = await this.Toolchain.GetEnvironment();
        const Arguments = ["-f", Result.NinjaPath];
        if (Options.Jobs) {
            Arguments.push("-j", String(Options.Jobs));
        }
        if (Options.Verbose) {
            Arguments.push("-v");
        }

        return new Promise((Resolve) => {
            const Process = ChildProcess.spawn(NinjaExecutable, Arguments, {
                cwd: Path.dirname(Result.NinjaPath),
                env: Environment,
                shell: false,
                stdio: "inherit",
            });
            Process.on("close", (ExitCode) => Resolve(ExitCode ?? 1));
            Process.on("error", (Error) => {
                console.error(`Failed to start ninja: ${Error.message}`);
                Resolve(1);
            });
        });
    }

    private BuildNinjaFile(Actions: BuildAction[], Target: Target): string {
        const Lines: string[] = [
            "# Auto-generated by LimitlessBuilder. Do not edit.",
            `# Target: ${Target.Platform} / ${Target.Optimization} / ${Target.TargetType}`,
            "ninja_required_version = 1.10",
            "",
            "rule cc",
            "    command = $Cmd",
            "    description = $Desc",
            "    deps = msvc",
            "    msvc_deps_prefix = Note: including file:",
            "",
            "rule link",
            "    command = $Cmd",
            "    description = $Desc",
            "",
            "rule archive",
            "    command = $Cmd",
            "    description = $Desc",
            "",
        ];

        for (const Action of Actions) {
            const RuleName = Action.Type === "compile" ? "cc"
                : Action.Type === "link" ? "link" : "archive";
            const Output = ToNinjaPath(Action.Outputs[0]);
            const Inputs = Action.Inputs.map(ToNinjaPath).join(" ");
            const Command = Action.Command.map(QuoteToken).join(" ");
            Lines.push(`build ${Output}: ${RuleName} ${Inputs}`);
            Lines.push(`    Cmd = ${Command}`);
            Lines.push(`    Desc = ${Action.Description}`);
            Lines.push("");
        }
        return Lines.join("\n");
    }

    private BuildCompileCommands(Actions: BuildAction[]): object[] {
        return Actions
            .filter((Action) => Action.Type === "compile")
            .map((Action) => ({
                directory: Action.WorkingDirectory,
                command: Action.Command.map(QuoteToken).join(" "),
                file: Action.Inputs[0],
            }));
    }
}
